### ISSUE TITLE
Implement MPI parallelisation over partitions

### ISSUE THREAD

**Issue by mylesDoyle** [JuliaQX/QXContexts.jl#17]
Parallelise MPI execution over partitions instead of over amplitudes. This involves

- refactor/reimplement `execute` in `QXContexts.jl/src/execution.jl`
     - change loop ordering; outer loop over partitions and inner over amplitudes
     - break loops into individual functions
- make function names more explicit instead of `execute`
- revise `partition` function appropriately to account for refactor

**Comment by nmoran** [comment]
@JuliaRegistrator register
